class AddLocationChinaData < ActiveRecord::Migration
  def self.up
    china = Country.create(:name => '中国内地')
    anhui = State.create(:name => '安徽')
    bj = State.create(:name => '北京')
    zq = State.create(:name => '重庆')
    qinghai = State.create(:name => '青海')
    fj = State.create(:name => '福建')
    gangs = State.create(:name => '甘肃')
    ningx = State.create(:name => '宁夏')
    gd = State.create(:name => '广东')
    gx = State.create(:name => '广西')
    guiz = State.create(:name => '贵州')
    hainan = State.create(:name => '海南')
    heib = State.create(:name => '河北')
    hlj = State.create(:name => '黑龙江')
    henan = State.create(:name => '河南')
    xiangg = State.create(:name => '香港')
    hb = State.create(:name => '湖北')
    hunan = State.create(:name => '湖南')
    js = State.create(:name => '江苏')
    jx = State.create(:name => '江西')
    jl = State.create(:name => '吉林')
    ln = State.create(:name => '辽宁')
    aomen = State.create(:name => '澳门')
    nmg = State.create(:name => '内蒙古')
    sanxi = State.create(:name => '陕西')
    sd = State.create(:name => '山东')
    sh = State.create(:name => '上海')
    sx = State.create(:name => '山西')
    sc = State.create(:name => '四川')
    tj = State.create(:name => '天津')
    xiz = State.create(:name => '西藏')
    xinj = State.create(:name => '新疆')
    yn = State.create(:name => '云南')
    zhejiang = State.create(:name => '浙江') 
    MetroArea.create(:name => '杭州',:country_id => china.id,:state_id => zhejiang.id)
    MetroArea.create(:name => '宁波',:country_id => china.id,:state_id => zhejiang.id)
    MetroArea.create(:name => '温州',:country_id => china.id,:state_id => zhejiang.id)
    MetroArea.create(:name => '嘉兴',:country_id => china.id,:state_id => zhejiang.id)
    MetroArea.create(:name => '台州',:country_id => china.id,:state_id => zhejiang.id)
    MetroArea.create(:name => '绍兴',:country_id => china.id,:state_id => zhejiang.id)
    MetroArea.create(:name => '金华',:country_id => china.id,:state_id => zhejiang.id)
    MetroArea.create(:name => '湖州',:country_id => china.id,:state_id => zhejiang.id)
    MetroArea.create(:name => '舟山',:country_id => china.id,:state_id => zhejiang.id)
    MetroArea.create(:name => '衢州',:country_id => china.id,:state_id => zhejiang.id)
    MetroArea.create(:name => '丽水',:country_id => china.id,:state_id => zhejiang.id)
    MetroArea.create(:name => '广州',:country_id => china.id,:state_id => gd.id)
    MetroArea.create(:name => '深圳',:country_id => china.id,:state_id => gd.id)
    MetroArea.create(:name => '珠海',:country_id => china.id,:state_id => gd.id)
    MetroArea.create(:name => '东莞',:country_id => china.id,:state_id => gd.id)
    MetroArea.create(:name => '佛山',:country_id => china.id,:state_id => gd.id)
    MetroArea.create(:name => '汕头',:country_id => china.id,:state_id => gd.id)
    MetroArea.create(:name => '中山',:country_id => china.id,:state_id => gd.id)
    MetroArea.create(:name => '惠州',:country_id => china.id,:state_id => gd.id)
    MetroArea.create(:name => '江门',:country_id => china.id,:state_id => gd.id)
    MetroArea.create(:name => '湛江 ',:country_id => china.id,:state_id => gd.id)
    MetroArea.create(:name => '潮州',:country_id => china.id,:state_id => gd.id)
    MetroArea.create(:name => '韶关',:country_id => china.id,:state_id => gd.id)
    MetroArea.create(:name => '肇庆',:country_id => china.id,:state_id => gd.id)
    MetroArea.create(:name => '茂名',:country_id => china.id,:state_id => gd.id)
    MetroArea.create(:name => '揭阳',:country_id => china.id,:state_id => gd.id)
    MetroArea.create(:name => '梅州',:country_id => china.id,:state_id => gd.id)
    MetroArea.create(:name => '清远',:country_id => china.id,:state_id => gd.id) 
    MetroArea.create(:name => '阳江',:country_id => china.id,:state_id => gd.id) 
    MetroArea.create(:name => '河源',:country_id => china.id,:state_id => gd.id) 
    MetroArea.create(:name => '汕尾',:country_id => china.id,:state_id => gd.id) 
    MetroArea.create(:name => '云浮',:country_id => china.id,:state_id => gd.id) 
    MetroArea.create(:name => '开平',:country_id => china.id,:state_id => gd.id) 
    MetroArea.create(:name => '南京',:country_id => china.id,:state_id => js.id)
    MetroArea.create(:name => '苏州',:country_id => china.id,:state_id => js.id)
    MetroArea.create(:name => '无锡',:country_id => china.id,:state_id => js.id)
    MetroArea.create(:name => '常州',:country_id => china.id,:state_id => js.id)
    MetroArea.create(:name => '徐州',:country_id => china.id,:state_id => js.id)
    MetroArea.create(:name => '扬州',:country_id => china.id,:state_id => js.id)
    MetroArea.create(:name => '南通',:country_id => china.id,:state_id => js.id)
    MetroArea.create(:name => '镇江',:country_id => china.id,:state_id => js.id)
    MetroArea.create(:name => '连云港',:country_id => china.id,:state_id => js.id)
    MetroArea.create(:name => '盐城',:country_id => china.id,:state_id => js.id)
    MetroArea.create(:name => '淮安',:country_id => china.id,:state_id => js.id) 
    MetroArea.create(:name => '泰州',:country_id => china.id,:state_id => js.id)
    MetroArea.create(:name => '宿迁',:country_id => china.id,:state_id => js.id)
    MetroArea.create(:name => '海安',:country_id => china.id,:state_id => js.id)
    MetroArea.create(:name => '武汉',:country_id => china.id,:state_id => hb.id)
    MetroArea.create(:name => '宜昌',:country_id => china.id,:state_id => hb.id)
    MetroArea.create(:name => '荆州',:country_id => china.id,:state_id => hb.id)
    MetroArea.create(:name => '襄樊',:country_id => china.id,:state_id => hb.id)
    MetroArea.create(:name => '黄石',:country_id => china.id,:state_id => hb.id)
    MetroArea.create(:name => '黄石',:country_id => china.id,:state_id => hb.id)
    MetroArea.create(:name => '孝感',:country_id => china.id,:state_id => hb.id)
    MetroArea.create(:name => '黄冈',:country_id => china.id,:state_id => hb.id)
    MetroArea.create(:name => '荆门',:country_id => china.id,:state_id => hb.id)
    MetroArea.create(:name => '恩施',:country_id => china.id,:state_id => hb.id)
    MetroArea.create(:name => '咸宁',:country_id => china.id,:state_id => hb.id)
    MetroArea.create(:name => '随州',:country_id => china.id,:state_id => hb.id)
    MetroArea.create(:name => '鄂州',:country_id => china.id,:state_id => hb.id)
    MetroArea.create(:name => '潜江',:country_id => china.id,:state_id => hb.id)
    MetroArea.create(:name => '仙桃',:country_id => china.id,:state_id => hb.id)
    MetroArea.create(:name => '天门',:country_id => china.id,:state_id => hb.id)
    MetroArea.create(:name => '成都',:country_id => china.id,:state_id => sc.id)
    MetroArea.create(:name => '绵阳',:country_id => china.id,:state_id => sc.id)
    MetroArea.create(:name => '德阳',:country_id => china.id,:state_id => sc.id)
    MetroArea.create(:name => '乐山',:country_id => china.id,:state_id => sc.id)
    MetroArea.create(:name => '自贡',:country_id => china.id,:state_id => sc.id)
    MetroArea.create(:name => '南充',:country_id => china.id,:state_id => sc.id)
    MetroArea.create(:name => '泸州',:country_id => china.id,:state_id => sc.id)
    MetroArea.create(:name => '内江',:country_id => china.id,:state_id => sc.id)
    MetroArea.create(:name => '宜宾',:country_id => china.id,:state_id => sc.id)
    MetroArea.create(:name => '遂宁',:country_id => china.id,:state_id => sc.id)
    MetroArea.create(:name => '达州',:country_id => china.id,:state_id => sc.id)
    MetroArea.create(:name => '雅安',:country_id => china.id,:state_id => sc.id)
    MetroArea.create(:name => '眉山',:country_id => china.id,:state_id => sc.id)
    MetroArea.create(:name => '攀枝花',:country_id => china.id,:state_id => sc.id)
    MetroArea.create(:name => '广安',:country_id => china.id,:state_id => sc.id)
    MetroArea.create(:name => '凉山',:country_id => china.id,:state_id => sc.id)
    MetroArea.create(:name => '广元',:country_id => china.id,:state_id => sc.id)
    MetroArea.create(:name => '资阳',:country_id => china.id,:state_id => sc.id)
    MetroArea.create(:name => '巴中',:country_id => china.id,:state_id => sc.id)
    MetroArea.create(:name => '阿坝',:country_id => china.id,:state_id => sc.id)
    MetroArea.create(:name => '甘孜',:country_id => china.id,:state_id => sc.id)
    MetroArea.create(:name => '青岛',:country_id => china.id,:state_id => sd.id)
    MetroArea.create(:name => '济南',:country_id => china.id,:state_id => sd.id)
    MetroArea.create(:name => '烟台',:country_id => china.id,:state_id => sd.id)
    MetroArea.create(:name => '淄博',:country_id => china.id,:state_id => sd.id)
    MetroArea.create(:name => '威海',:country_id => china.id,:state_id => sd.id)
    MetroArea.create(:name => '潍坊',:country_id => china.id,:state_id => sd.id)
    MetroArea.create(:name => '济宁',:country_id => china.id,:state_id => sd.id)
    MetroArea.create(:name => '临沂',:country_id => china.id,:state_id => sd.id)
    MetroArea.create(:name => '东营',:country_id => china.id,:state_id => sd.id)
    MetroArea.create(:name => '泰安',:country_id => china.id,:state_id => sd.id)
    MetroArea.create(:name => '日照',:country_id => china.id,:state_id => sd.id)
    MetroArea.create(:name => '枣庄',:country_id => china.id,:state_id => sd.id)
    MetroArea.create(:name => '聊城',:country_id => china.id,:state_id => sd.id)
    MetroArea.create(:name => '菏泽',:country_id => china.id,:state_id => sd.id)
    MetroArea.create(:name => '德州',:country_id => china.id,:state_id => sd.id)
    MetroArea.create(:name => '滨州',:country_id => china.id,:state_id => sd.id)
    MetroArea.create(:name => '莱芜',:country_id => china.id,:state_id => sd.id)
    MetroArea.create(:name => '厦门',:country_id => china.id,:state_id => fj.id)
    MetroArea.create(:name => '福州',:country_id => china.id,:state_id => fj.id)
    MetroArea.create(:name => '泉州',:country_id => china.id,:state_id => fj.id)
    MetroArea.create(:name => '漳州',:country_id => china.id,:state_id => fj.id)
    MetroArea.create(:name => '莆田',:country_id => china.id,:state_id => fj.id)
    MetroArea.create(:name => '龙岩',:country_id => china.id,:state_id => fj.id)
    MetroArea.create(:name => '三明',:country_id => china.id,:state_id => fj.id)
    MetroArea.create(:name => '宁德',:country_id => china.id,:state_id => fj.id)
    MetroArea.create(:name => '南平',:country_id => china.id,:state_id => fj.id)
    MetroArea.create(:name => '西安',:country_id => china.id,:state_id => sanxi.id)
    MetroArea.create(:name => '咸阳',:country_id => china.id,:state_id => sanxi.id)
    MetroArea.create(:name => '宝鸡',:country_id => china.id,:state_id => sanxi.id)
    MetroArea.create(:name => '汉中',:country_id => china.id,:state_id => sanxi.id)
    MetroArea.create(:name => '榆林',:country_id => china.id,:state_id => sanxi.id)
    MetroArea.create(:name => '延安',:country_id => china.id,:state_id => sanxi.id)
    MetroArea.create(:name => '安康',:country_id => china.id,:state_id => sanxi.id)
    MetroArea.create(:name => '商洛',:country_id => china.id,:state_id => sanxi.id)
    MetroArea.create(:name => '铜川',:country_id => china.id,:state_id => sanxi.id)
    MetroArea.create(:name => '石家庄',:country_id => china.id,:state_id => heib.id)
    MetroArea.create(:name => '保定',:country_id => china.id,:state_id => heib.id)
    MetroArea.create(:name => '秦皇岛',:country_id => china.id,:state_id => heib.id)
    MetroArea.create(:name => '唐山',:country_id => china.id,:state_id => heib.id)
    MetroArea.create(:name => '邯郸',:country_id => china.id,:state_id => heib.id)
    MetroArea.create(:name => '廊坊',:country_id => china.id,:state_id => heib.id)
    MetroArea.create(:name => '邢台',:country_id => china.id,:state_id => heib.id)
    MetroArea.create(:name => '沧州',:country_id => china.id,:state_id => heib.id)
    MetroArea.create(:name => '承德',:country_id => china.id,:state_id => heib.id)
    MetroArea.create(:name => '张家口',:country_id => china.id,:state_id => heib.id)
    MetroArea.create(:name => '衡水',:country_id => china.id,:state_id => heib.id)
    MetroArea.create(:name => '大连',:country_id => china.id,:state_id => ln.id)
    MetroArea.create(:name => '沈阳 ',:country_id => china.id,:state_id => ln.id)
    MetroArea.create(:name => '鞍山',:country_id => china.id,:state_id => ln.id)
    MetroArea.create(:name => '锦州',:country_id => china.id,:state_id => ln.id)
    MetroArea.create(:name => '抚顺',:country_id => china.id,:state_id => ln.id)
    MetroArea.create(:name => '营口',:country_id => china.id,:state_id => ln.id)
    MetroArea.create(:name => '葫芦岛',:country_id => china.id,:state_id => ln.id)
    MetroArea.create(:name => '盘锦',:country_id => china.id,:state_id => ln.id)
    MetroArea.create(:name => '本溪',:country_id => china.id,:state_id => ln.id)
    MetroArea.create(:name => '朝阳',:country_id => china.id,:state_id => ln.id)
    MetroArea.create(:name => '铁岭',:country_id => china.id,:state_id => ln.id)
    MetroArea.create(:name => '阜新',:country_id => china.id,:state_id => ln.id)
    MetroArea.create(:name => '辽阳',:country_id => china.id,:state_id => ln.id)
    MetroArea.create(:name => '南宁',:country_id => china.id,:state_id => gx.id)
    MetroArea.create(:name => '桂林',:country_id => china.id,:state_id => gx.id)
    MetroArea.create(:name => '柳州',:country_id => china.id,:state_id => gx.id)
    MetroArea.create(:name => '玉林',:country_id => china.id,:state_id => gx.id)
    MetroArea.create(:name => '北海',:country_id => china.id,:state_id => gx.id)
    MetroArea.create(:name => '梧州',:country_id => china.id,:state_id => gx.id)
    MetroArea.create(:name => '河池',:country_id => china.id,:state_id => gx.id)
    MetroArea.create(:name => '百色',:country_id => china.id,:state_id => gx.id)
    MetroArea.create(:name => '贵港',:country_id => china.id,:state_id => gx.id)
    MetroArea.create(:name => '钦州',:country_id => china.id,:state_id => gx.id)
    MetroArea.create(:name => '贺州',:country_id => china.id,:state_id => gx.id)
    MetroArea.create(:name => '防城港',:country_id => china.id,:state_id => gx.id)
    MetroArea.create(:name => '崇左',:country_id => china.id,:state_id => gx.id)
    MetroArea.create(:name => '来宾',:country_id => china.id,:state_id => gx.id)
    MetroArea.create(:name => '南昌',:country_id => china.id,:state_id => jx.id) 
    MetroArea.create(:name => '赣州',:country_id => china.id,:state_id => jx.id)
    MetroArea.create(:name => '九江',:country_id => china.id,:state_id => jx.id)
    MetroArea.create(:name => '景德镇',:country_id => china.id,:state_id => jx.id)
    MetroArea.create(:name => '上饶',:country_id => china.id,:state_id => jx.id)
    MetroArea.create(:name => '宜春',:country_id => china.id,:state_id => jx.id)
    MetroArea.create(:name => '萍乡',:country_id => china.id,:state_id => jx.id)
    MetroArea.create(:name => '新余',:country_id => china.id,:state_id => jx.id)
    MetroArea.create(:name => '吉安',:country_id => china.id,:state_id => jx.id)
    MetroArea.create(:name => '抚州',:country_id => china.id,:state_id => jx.id)
    MetroArea.create(:name => '鹰潭',:country_id => china.id,:state_id => jx.id)
    MetroArea.create(:name => '长春',:country_id => china.id,:state_id => jl.id)
    MetroArea.create(:name => '吉林',:country_id => china.id,:state_id => jl.id)
    MetroArea.create(:name => '延边',:country_id => china.id,:state_id => jl.id)
    MetroArea.create(:name => '通化',:country_id => china.id,:state_id => jl.id)
    MetroArea.create(:name => '四平',:country_id => china.id,:state_id => jl.id)
    MetroArea.create(:name => '松原',:country_id => china.id,:state_id => jl.id)
    MetroArea.create(:name => '白山',:country_id => china.id,:state_id => jl.id)
    MetroArea.create(:name => '白城',:country_id => china.id,:state_id => jl.id)
    MetroArea.create(:name => '辽源',:country_id => china.id,:state_id => jl.id)
    MetroArea.create(:name => '太原',:country_id => china.id,:state_id => sx.id)
    MetroArea.create(:name => '临汾',:country_id => china.id,:state_id => sx.id)
    MetroArea.create(:name => '大同',:country_id => china.id,:state_id => sx.id)
    MetroArea.create(:name => '运城',:country_id => china.id,:state_id => sx.id)
    MetroArea.create(:name => '晋城',:country_id => china.id,:state_id => sx.id)
    MetroArea.create(:name => '长治',:country_id => china.id,:state_id => sx.id)
    MetroArea.create(:name => '晋中',:country_id => china.id,:state_id => sx.id)
    MetroArea.create(:name => '吕梁',:country_id => china.id,:state_id => sx.id)
    MetroArea.create(:name => '阳泉',:country_id => china.id,:state_id => sx.id)
    MetroArea.create(:name => '忻州',:country_id => china.id,:state_id => sx.id)
    MetroArea.create(:name => '朔州',:country_id => china.id,:state_id => sx.id)
    MetroArea.create(:name => '大宁',:country_id => china.id,:state_id => sx.id)
    MetroArea.create(:name => '昆明',:country_id => china.id,:state_id => yn.id)
    MetroArea.create(:name => '丽江',:country_id => china.id,:state_id => yn.id)
    MetroArea.create(:name => '大理',:country_id => china.id,:state_id => yn.id)
    MetroArea.create(:name => '曲靖',:country_id => china.id,:state_id => yn.id)
    MetroArea.create(:name => '玉溪',:country_id => china.id,:state_id => yn.id)
    MetroArea.create(:name => '红河',:country_id => china.id,:state_id => yn.id)
    MetroArea.create(:name => '楚雄',:country_id => china.id,:state_id => yn.id)
    MetroArea.create(:name => '保山',:country_id => china.id,:state_id => yn.id)
    MetroArea.create(:name => '昭通',:country_id => china.id,:state_id => yn.id)
    MetroArea.create(:name => '文山',:country_id => china.id,:state_id => yn.id)
    MetroArea.create(:name => '思茅',:country_id => china.id,:state_id => yn.id)
    MetroArea.create(:name => '西双版纳',:country_id => china.id,:state_id => yn.id)
    MetroArea.create(:name => '临沧',:country_id => china.id,:state_id => yn.id)
    MetroArea.create(:name => '德宏',:country_id => china.id,:state_id => yn.id)
    MetroArea.create(:name => '怒江',:country_id => china.id,:state_id => yn.id)
    MetroArea.create(:name => '迪庆',:country_id => china.id,:state_id => yn.id)
    MetroArea.create(:name => '合肥',:country_id => china.id,:state_id => anhui.id)
    MetroArea.create(:name => '芜湖',:country_id => china.id,:state_id => anhui.id) 
    MetroArea.create(:name => '安庆',:country_id => china.id,:state_id => anhui.id) 
    MetroArea.create(:name => '马鞍山',:country_id => china.id,:state_id => anhui.id) 
    MetroArea.create(:name => '蚌埠',:country_id => china.id,:state_id => anhui.id) 
    MetroArea.create(:name => '铜陵',:country_id => china.id,:state_id => anhui.id) 
    MetroArea.create(:name => '淮南',:country_id => china.id,:state_id => anhui.id) 
    MetroArea.create(:name => '黄山',:country_id => china.id,:state_id => anhui.id) 
    MetroArea.create(:name => '滁州',:country_id => china.id,:state_id => anhui.id) 
    MetroArea.create(:name => '淮北',:country_id => china.id,:state_id => anhui.id) 
    MetroArea.create(:name => '阜阳',:country_id => china.id,:state_id => anhui.id) 
    MetroArea.create(:name => '巢湖',:country_id => china.id,:state_id => anhui.id) 
    MetroArea.create(:name => '六安',:country_id => china.id,:state_id => anhui.id) 
    MetroArea.create(:name => '宣城',:country_id => china.id,:state_id => anhui.id) 
    MetroArea.create(:name => '宿州',:country_id => china.id,:state_id => anhui.id) 
    MetroArea.create(:name => '池州',:country_id => china.id,:state_id => anhui.id) 
    MetroArea.create(:name => '亳州',:country_id => china.id,:state_id => anhui.id) 
    MetroArea.create(:name => '哈尔滨',:country_id => china.id,:state_id => hlj.id)
    MetroArea.create(:name => '大庆',:country_id => china.id,:state_id => hlj.id)
    MetroArea.create(:name => '齐齐哈尔',:country_id => china.id,:state_id => hlj.id)
    MetroArea.create(:name => '牡丹江',:country_id => china.id,:state_id => hlj.id)
    MetroArea.create(:name => '佳木斯',:country_id => china.id,:state_id => hlj.id)
    MetroArea.create(:name => '鸡西',:country_id => china.id,:state_id => hlj.id)
    MetroArea.create(:name => '绥化',:country_id => china.id,:state_id => hlj.id)
    MetroArea.create(:name => '鹤岗',:country_id => china.id,:state_id => hlj.id)
    MetroArea.create(:name => '双鸭山',:country_id => china.id,:state_id => hlj.id)
    MetroArea.create(:name => '伊春',:country_id => china.id,:state_id => hlj.id)
    MetroArea.create(:name => '黑河',:country_id => china.id,:state_id => hlj.id)
    MetroArea.create(:name => '七台河',:country_id => china.id,:state_id => hlj.id)
    MetroArea.create(:name => '大兴安岭',:country_id => china.id,:state_id => hlj.id)
    MetroArea.create(:name => '长沙',:country_id => china.id,:state_id => hunan.id)
    MetroArea.create(:name => '株洲',:country_id => china.id,:state_id => hunan.id)
    MetroArea.create(:name => '湘潭',:country_id => china.id,:state_id => hunan.id)
    MetroArea.create(:name => '衡阳',:country_id => china.id,:state_id => hunan.id)
    MetroArea.create(:name => '岳阳',:country_id => china.id,:state_id => hunan.id)
    MetroArea.create(:name => '常德',:country_id => china.id,:state_id => hunan.id)
    MetroArea.create(:name => '郴州',:country_id => china.id,:state_id => hunan.id)
    MetroArea.create(:name => '怀化',:country_id => china.id,:state_id => hunan.id)
    MetroArea.create(:name => '邵阳',:country_id => china.id,:state_id => hunan.id)
    MetroArea.create(:name => '益阳',:country_id => china.id,:state_id => hunan.id)
    MetroArea.create(:name => '湘西',:country_id => china.id,:state_id => hunan.id)
    MetroArea.create(:name => '永州',:country_id => china.id,:state_id => hunan.id)
    MetroArea.create(:name => '娄底',:country_id => china.id,:state_id => hunan.id) 
    MetroArea.create(:name => '张家界',:country_id => china.id,:state_id => hunan.id)
    MetroArea.create(:name => '郑州',:country_id => china.id,:state_id => henan.id)
    MetroArea.create(:name => '洛阳',:country_id => china.id,:state_id => henan.id)
    MetroArea.create(:name => '新乡',:country_id => china.id,:state_id => henan.id)
    MetroArea.create(:name => '开封 ',:country_id => china.id,:state_id => henan.id)
    MetroArea.create(:name => '南阳',:country_id => china.id,:state_id => henan.id)
    MetroArea.create(:name => '安阳',:country_id => china.id,:state_id => henan.id)
    MetroArea.create(:name => '平顶山',:country_id => china.id,:state_id => henan.id)
    MetroArea.create(:name => '焦作',:country_id => china.id,:state_id => henan.id)
    MetroArea.create(:name => '商丘',:country_id => china.id,:state_id => henan.id)
    MetroArea.create(:name => '许昌',:country_id => china.id,:state_id => henan.id)
    MetroArea.create(:name => '濮阳',:country_id => china.id,:state_id => henan.id)
    MetroArea.create(:name => '信阳',:country_id => china.id,:state_id => henan.id)
    MetroArea.create(:name => '周口',:country_id => china.id,:state_id => henan.id)
    MetroArea.create(:name => '驻马店',:country_id => china.id,:state_id => henan.id)
    MetroArea.create(:name => '三门峡',:country_id => china.id,:state_id => henan.id)
    MetroArea.create(:name => '漯河',:country_id => china.id,:state_id => henan.id)
    MetroArea.create(:name => '鹤壁',:country_id => china.id,:state_id => henan.id)
    MetroArea.create(:name => '贵阳',:country_id => china.id,:state_id => guiz.id) 
    MetroArea.create(:name => '遵义',:country_id => china.id,:state_id => guiz.id)
    MetroArea.create(:name => '安顺',:country_id => china.id,:state_id => guiz.id)
    MetroArea.create(:name => '黔东南',:country_id => china.id,:state_id => guiz.id)
    MetroArea.create(:name => '六盘水',:country_id => china.id,:state_id => guiz.id)
    MetroArea.create(:name => '黔南',:country_id => china.id,:state_id => guiz.id)
    MetroArea.create(:name => '铜仁',:country_id => china.id,:state_id => guiz.id)
    MetroArea.create(:name => '黔西南',:country_id => china.id,:state_id => guiz.id)
    MetroArea.create(:name => '毕节',:country_id => china.id,:state_id => guiz.id)
    MetroArea.create(:name => '呼和浩特',:country_id => china.id,:state_id => nmg.id)
    MetroArea.create(:name => '包头',:country_id => china.id,:state_id => nmg.id)
    MetroArea.create(:name => '  呼伦贝尔',:country_id => china.id,:state_id => nmg.id)
    MetroArea.create(:name => '赤峰',:country_id => china.id,:state_id => nmg.id)
    MetroArea.create(:name => '鄂尔多斯',:country_id => china.id,:state_id => nmg.id)
    MetroArea.create(:name => '通辽',:country_id => china.id,:state_id => nmg.id)
    MetroArea.create(:name => '锡林郭勒',:country_id => china.id,:state_id => nmg.id)
    MetroArea.create(:name => '巴彦淖尔',:country_id => china.id,:state_id => nmg.id)
    MetroArea.create(:name => '乌海',:country_id => china.id,:state_id => nmg.id)
    MetroArea.create(:name => '阿拉善',:country_id => china.id,:state_id => nmg.id)
    MetroArea.create(:name => '兴安',:country_id => china.id,:state_id => nmg.id)
    MetroArea.create(:name => '乌兰察布',:country_id => china.id,:state_id => nmg.id)
    MetroArea.create(:name => '海口',:country_id => china.id,:state_id => hainan.id)
    MetroArea.create(:name => '三亚',:country_id => china.id,:state_id => hainan.id)
    MetroArea.create(:name => '银川',:country_id => china.id,:state_id => ningx.id)
    MetroArea.create(:name => '石嘴山',:country_id => china.id,:state_id => ningx.id)
    MetroArea.create(:name => '吴忠',:country_id => china.id,:state_id => ningx.id)
    MetroArea.create(:name => '固原',:country_id => china.id,:state_id => ningx.id)
    MetroArea.create(:name => '中卫',:country_id => china.id,:state_id => ningx.id)
    MetroArea.create(:name => '兰州',:country_id => china.id,:state_id => gangs.id)
    MetroArea.create(:name => '天水',:country_id => china.id,:state_id => gangs.id)
    MetroArea.create(:name => '平凉',:country_id => china.id,:state_id => gangs.id)
    MetroArea.create(:name => '酒泉',:country_id => china.id,:state_id => gangs.id)
    MetroArea.create(:name => '白银',:country_id => china.id,:state_id => gangs.id)
    MetroArea.create(:name => '庆阳',:country_id => china.id,:state_id => gangs.id)
    MetroArea.create(:name => '武威',:country_id => china.id,:state_id => gangs.id)
    MetroArea.create(:name => '张掖',:country_id => china.id,:state_id => gangs.id)
    MetroArea.create(:name => '定西',:country_id => china.id,:state_id => gangs.id)
    MetroArea.create(:name => '陇南',:country_id => china.id,:state_id => gangs.id)
    MetroArea.create(:name => '临夏',:country_id => china.id,:state_id => gangs.id)
    MetroArea.create(:name => '金昌',:country_id => china.id,:state_id => gangs.id)
    MetroArea.create(:name => '甘南',:country_id => china.id,:state_id => gangs.id)
    MetroArea.create(:name => '西宁',:country_id => china.id,:state_id => qinghai.id)
    MetroArea.create(:name => '果洛',:country_id => china.id,:state_id => qinghai.id)
    MetroArea.create(:name => '海东',:country_id => china.id,:state_id => qinghai.id)
    MetroArea.create(:name => '海西',:country_id => china.id,:state_id => qinghai.id)
    MetroArea.create(:name => '海北',:country_id => china.id,:state_id => qinghai.id)
    MetroArea.create(:name => '海南',:country_id => china.id,:state_id => qinghai.id)
    MetroArea.create(:name => '玉树',:country_id => china.id,:state_id => qinghai.id)
    MetroArea.create(:name => '黄南',:country_id => china.id,:state_id => qinghai.id)
    MetroArea.create(:name => '拉萨',:country_id => china.id,:state_id => xiz.id) 
    MetroArea.create(:name => '那曲',:country_id => china.id,:state_id => xiz.id)
    MetroArea.create(:name => '日喀则',:country_id => china.id,:state_id => xiz.id)
    MetroArea.create(:name => '林芝',:country_id => china.id,:state_id => xiz.id)
    MetroArea.create(:name => '阿里',:country_id => china.id,:state_id => xiz.id)
    MetroArea.create(:name => '昌都',:country_id => china.id,:state_id => xiz.id)
    MetroArea.create(:name => '山南',:country_id => china.id,:state_id => xiz.id)
    MetroArea.create(:name => '乌鲁木齐',:country_id => china.id,:state_id => xinj.id)
    MetroArea.create(:name => '克拉玛依',:country_id => china.id,:state_id => xinj.id)
    MetroArea.create(:name => '巴音郭楞',:country_id => china.id,:state_id => xinj.id)
    MetroArea.create(:name => '昌吉',:country_id => china.id,:state_id => xinj.id)
    MetroArea.create(:name => '伊犁',:country_id => china.id,:state_id => xinj.id)
    MetroArea.create(:name => '哈密',:country_id => china.id,:state_id => xinj.id)
    MetroArea.create(:name => '阿克苏',:country_id => china.id,:state_id => xinj.id)
    MetroArea.create(:name => '喀什',:country_id => china.id,:state_id => xinj.id)
    MetroArea.create(:name => '北京',:country_id => china.id,:state_id => bj.id)
    MetroArea.create(:name => '重庆',:country_id => china.id,:state_id => zq.id)
    MetroArea.create(:name => '香港',:country_id => china.id,:state_id => xiangg.id)
    MetroArea.create(:name => '天津',:country_id => china.id,:state_id => tj.id)
    MetroArea.create(:name => '上海',:country_id => china.id,:state_id => sh.id)
    MetroArea.create(:name => '澳门',:country_id => china.id,:state_id => aomen.id)
  end

  def self.down
  end
end
